//replace: \ESP32_USB_STREAM\src\original\include\arduino_config.h
#define CONFIG_USB_PROC_TASK_STACK_SIZE 4096    // 增大栈大小
#define CONFIG_USB_PROC_TASK_PRIORITY 5
#define CONFIG_USB_PROC_TASK_CORE 1 //S2:0 S3:1

// 采样处理任务
#define CONFIG_SAMPLE_PROC_TASK_STACK_SIZE 4096 // 增大
#define CONFIG_SAMPLE_PROC_TASK_PRIORITY 2
#define CONFIG_SAMPLE_PROC_TASK_CORE 0

// 控制传输
#define CONFIG_CTRL_TRANSFER_DATA_MAX_BYTES 1024
#define CONFIG_USB_PRE_ALLOC_CTRL_TRANSFER_URB 1
#define CONFIG_USB_CTRL_XFER_TIMEOUT_MS 1000

// UVC摄像头配置 - 关键修改！
#define CONFIG_UVC_GET_DEVICE_DESC 1
#define CONFIG_UVC_GET_CONFIG_DESC 1
#define CONFIG_UVC_PRINT_DESC 1
#define CONFIG_UVC_PRINT_PROBE_RESULT 1

// 帧处理配置
#define CONFIG_UVC_CHECK_BULK_JPEG_HEADER 1
#define CONFIG_UVC_DROP_OVERFLOW_FRAME 1        // 改为0，不丢弃溢出帧
#define CONFIG_UVC_MAX_FRAME_BUFFER_SIZE (64 * 1024)  // 添加：最大帧缓冲区

// Bulk传输配置（增大！）
#define CONFIG_NUM_BULK_STREAM_URBS 4           // 增加URB数量
#define CONFIG_NUM_BULK_BYTES_PER_URB (32 * 1024) // 增大到32KB

// ISOC传输配置
#define CONFIG_NUM_ISOC_UVC_URBS 4              // 增加
#define CONFIG_NUM_PACKETS_PER_URB 8            // 增加包数量

// UAC音频配置
#define CONFIG_NUM_ISOC_SPK_URBS 6
#define CONFIG_NUM_ISOC_MIC_URBS 3
#define CONFIG_UAC_MIC_CB_MIN_MS_DEFAULT 16
#define CONFIG_UAC_SPK_ST_MAX_MS_DEFAULT 16
#define CONFIG_UAC_SPK_VOLUME_LEVEL_DEFAULT 80
#define CONFIG_UAC_MIC_VOLUME_LEVEL_DEFAULT 80
#define CONFIG_UAC_MIC_PACKET_COMPENSATION 1
#define CONFIG_UAC_SPK_PACKET_COMPENSATION 1
#define CONFIG_UAC_SPK_PACKET_COMPENSATION_SIZE_MS 10
#define CONFIG_UAC_SPK_PACKET_COMPENSATION_TIMEOUT_MS 1000

// USB枚举和连接
#define CONFIG_USB_WAITING_AFTER_CONN_MS 50
#define CONFIG_USB_ENUM_FAILED_RETRY 1
#define CONFIG_USB_ENUM_FAILED_RETRY_COUNT 10
#define CONFIG_USB_ENUM_FAILED_RETRY_DELAY_MS 200

// 版本信息
#define USB_STREAM_VER_MAJOR 1
#define USB_STREAM_VER_MINOR 4
#define USB_STREAM_VER_PATCH 0